# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_US_ui.ui'
#
# Created: Wed Oct 22 12:57:33 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogUS(object):
    def setupUi(self, DialogUS):
        DialogUS.setObjectName(_fromUtf8("DialogUS"))
        DialogUS.resize(738, 775)
        DialogUS.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconPAI.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogUS.setWindowIcon(icon)
        self.gridLayout_10 = QtGui.QGridLayout(DialogUS)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogUS)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogUS)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 3, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_last_rec = QtGui.QPushButton(DialogUS)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon1)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon2)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon3)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon4)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon5)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon6)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon7)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(DialogUS)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon8)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogUS)
        self.pushButton_prev_rec.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon9)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 3, 1, 1)
        self.pushButton_first_rec = QtGui.QPushButton(DialogUS)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon10)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 2, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogUS)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon11)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogUS)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 0, 0, 2, 2)
        self.line_8 = QtGui.QFrame(DialogUS)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_10.addWidget(self.line_8, 1, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_sito = QtGui.QComboBox(DialogUS)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_sito)
        self.comboBox_area = QtGui.QComboBox(DialogUS)
        self.comboBox_area.setEnabled(False)
        self.comboBox_area.setMaximumSize(QtCore.QSize(64, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setEditable(True)
        self.comboBox_area.setObjectName(_fromUtf8("comboBox_area"))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_area)
        self.lineEdit_us = QtGui.QLineEdit(DialogUS)
        self.lineEdit_us.setEnabled(False)
        self.lineEdit_us.setMinimumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_us.setFont(font)
        self.lineEdit_us.setObjectName(_fromUtf8("lineEdit_us"))
        self.horizontalLayout_2.addWidget(self.lineEdit_us)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(DialogUS)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(303, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(DialogUS)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(DialogUS)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(97, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.comboBox_def_strat = QtGui.QComboBox(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_def_strat.setFont(font)
        self.comboBox_def_strat.setEditable(True)
        self.comboBox_def_strat.setObjectName(_fromUtf8("comboBox_def_strat"))
        self.gridLayout_6.addWidget(self.comboBox_def_strat, 0, 0, 1, 1)
        self.comboBox_def_intepret = QtGui.QComboBox(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_def_intepret.setFont(font)
        self.comboBox_def_intepret.setEditable(True)
        self.comboBox_def_intepret.setObjectName(_fromUtf8("comboBox_def_intepret"))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.comboBox_def_intepret.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_def_intepret, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(DialogUS)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(DialogUS)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 3, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(DialogUS)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.textEdit_descrizione = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione.setFont(font)
        self.textEdit_descrizione.setObjectName(_fromUtf8("textEdit_descrizione"))
        self.verticalLayout_5.addWidget(self.textEdit_descrizione)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione.setFont(font)
        self.textEdit_interpretazione.setObjectName(_fromUtf8("textEdit_interpretazione"))
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_15.addWidget(self.label_12, 0, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_15.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_15.addWidget(self.label_14, 1, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setMinimumSize(QtCore.QSize(0, 15))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_15.addWidget(self.label_18, 1, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setMinimumSize(QtCore.QSize(0, 15))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_15.addWidget(self.label_22, 1, 6, 1, 1)
        self.comboBox_per_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_iniz.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_per_iniz.setObjectName(_fromUtf8("comboBox_per_iniz"))
        self.gridLayout_15.addWidget(self.comboBox_per_iniz, 3, 0, 1, 1)
        self.lineEdit_attivita = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_attivita.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_attivita.setFont(font)
        self.lineEdit_attivita.setObjectName(_fromUtf8("lineEdit_attivita"))
        self.gridLayout_15.addWidget(self.lineEdit_attivita, 3, 5, 1, 1)
        self.lineEdit_struttura = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_struttura.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_struttura.setFont(font)
        self.lineEdit_struttura.setObjectName(_fromUtf8("lineEdit_struttura"))
        self.gridLayout_15.addWidget(self.lineEdit_struttura, 3, 6, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_15.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_15.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_15.addWidget(self.label_32, 4, 4, 1, 1)
        self.comboBox_fas_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_iniz.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_fas_iniz.setObjectName(_fromUtf8("comboBox_fas_iniz"))
        self.gridLayout_15.addWidget(self.comboBox_fas_iniz, 3, 1, 1, 1)
        self.comboBox_per_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_fin.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_per_fin.setObjectName(_fromUtf8("comboBox_per_fin"))
        self.gridLayout_15.addWidget(self.comboBox_per_fin, 3, 3, 1, 1)
        self.comboBox_fas_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_fin.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_fas_fin.setObjectName(_fromUtf8("comboBox_fas_fin"))
        self.gridLayout_15.addWidget(self.comboBox_fas_fin, 3, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_15)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.lineEdit_anno = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_anno.setObjectName(_fromUtf8("lineEdit_anno"))
        self.gridLayout_16.addWidget(self.lineEdit_anno, 0, 2, 1, 1)
        self.comboBox_metodo = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_metodo.setFont(font)
        self.comboBox_metodo.setEditable(True)
        self.comboBox_metodo.setObjectName(_fromUtf8("comboBox_metodo"))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_metodo, 0, 4, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_16.addWidget(self.label_33, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_16.addWidget(self.label_17, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 0, 3, 1, 1)
        self.comboBox_scavato = QtGui.QComboBox(self.tab_2)
        self.comboBox_scavato.setEditable(True)
        self.comboBox_scavato.setObjectName(_fromUtf8("comboBox_scavato"))
        self.comboBox_scavato.addItem(_fromUtf8(""))
        self.comboBox_scavato.setItemText(0, _fromUtf8(""))
        self.comboBox_scavato.addItem(_fromUtf8(""))
        self.comboBox_scavato.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_scavato, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_16.addWidget(self.label_8, 1, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_16)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_10.addWidget(self.line_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_4.addWidget(self.label_19)
        self.pushButton_insert_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rapporti.setFont(font)
        self.pushButton_insert_row_rapporti.setObjectName(_fromUtf8("pushButton_insert_row_rapporti"))
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_rapporti)
        self.pushButton_remove_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_rapporti.setFont(font)
        self.pushButton_remove_row_rapporti.setObjectName(_fromUtf8("pushButton_remove_row_rapporti"))
        self.horizontalLayout_4.addWidget(self.pushButton_remove_row_rapporti)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tableWidget_rapporti = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_rapporti.setEnabled(True)
        self.tableWidget_rapporti.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rapporti.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rapporti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rapporti.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_rapporti.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_rapporti.setRowCount(1)
        self.tableWidget_rapporti.setColumnCount(2)
        self.tableWidget_rapporti.setObjectName(_fromUtf8("tableWidget_rapporti"))
        self.tableWidget_rapporti.setColumnCount(2)
        self.tableWidget_rapporti.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(1, item)
        self.verticalLayout_14.addWidget(self.tableWidget_rapporti)
        self.pushButton_go_to_us = QtGui.QPushButton(self.tab_2)
        self.pushButton_go_to_us.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_go_to_us.setObjectName(_fromUtf8("pushButton_go_to_us"))
        self.verticalLayout_14.addWidget(self.pushButton_go_to_us)
        self.gridLayout_17.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.comboBox_formazione = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_formazione.setFont(font)
        self.comboBox_formazione.setEditable(True)
        self.comboBox_formazione.setObjectName(_fromUtf8("comboBox_formazione"))
        self.comboBox_formazione.addItem(_fromUtf8(""))
        self.comboBox_formazione.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox_formazione, 0, 0, 1, 1)
        self.tableWidget_inclusi = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_inclusi.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_inclusi.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_inclusi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_inclusi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_inclusi.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_inclusi.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_inclusi.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_inclusi.setRowCount(1)
        self.tableWidget_inclusi.setColumnCount(1)
        self.tableWidget_inclusi.setObjectName(_fromUtf8("tableWidget_inclusi"))
        self.tableWidget_inclusi.setColumnCount(1)
        self.tableWidget_inclusi.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_inclusi.setHorizontalHeaderItem(0, item)
        self.gridLayout_14.addWidget(self.tableWidget_inclusi, 0, 1, 6, 2)
        self.tableWidget_campioni = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_campioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_campioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_campioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_campioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_campioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_campioni.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_campioni.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_campioni.setRowCount(1)
        self.tableWidget_campioni.setColumnCount(1)
        self.tableWidget_campioni.setObjectName(_fromUtf8("tableWidget_campioni"))
        self.tableWidget_campioni.setColumnCount(1)
        self.tableWidget_campioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_campioni.setHorizontalHeaderItem(0, item)
        self.gridLayout_14.addWidget(self.tableWidget_campioni, 0, 3, 6, 2)
        self.label_20 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_14.addWidget(self.label_20, 1, 0, 1, 1)
        self.comboBox_colore = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_colore.setFont(font)
        self.comboBox_colore.setEditable(True)
        self.comboBox_colore.setObjectName(_fromUtf8("comboBox_colore"))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.comboBox_colore.setItemText(8, _fromUtf8(""))
        self.comboBox_colore.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox_colore, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_14.addWidget(self.label_21, 3, 0, 1, 1)
        self.comboBox_consistenza = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_consistenza.setFont(font)
        self.comboBox_consistenza.setEditable(True)
        self.comboBox_consistenza.setObjectName(_fromUtf8("comboBox_consistenza"))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.comboBox_consistenza.setItemText(5, _fromUtf8(""))
        self.comboBox_consistenza.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox_consistenza, 4, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_14.addWidget(self.label_26, 5, 0, 1, 1)
        self.comboBox_conservazione = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_conservazione.setFont(font)
        self.comboBox_conservazione.setEditable(True)
        self.comboBox_conservazione.setObjectName(_fromUtf8("comboBox_conservazione"))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox_conservazione, 6, 0, 1, 1)
        self.pushButton_insert_row_inclusi = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_inclusi.setFont(font)
        self.pushButton_insert_row_inclusi.setObjectName(_fromUtf8("pushButton_insert_row_inclusi"))
        self.gridLayout_14.addWidget(self.pushButton_insert_row_inclusi, 6, 1, 1, 1)
        self.pushButton_remove_row_inclusi = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_inclusi.setFont(font)
        self.pushButton_remove_row_inclusi.setObjectName(_fromUtf8("pushButton_remove_row_inclusi"))
        self.gridLayout_14.addWidget(self.pushButton_remove_row_inclusi, 6, 2, 1, 1)
        self.pushButton_insert_row_campioni = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_campioni.setFont(font)
        self.pushButton_insert_row_campioni.setObjectName(_fromUtf8("pushButton_insert_row_campioni"))
        self.gridLayout_14.addWidget(self.pushButton_insert_row_campioni, 6, 3, 1, 1)
        self.pushButton_remove_row_campioni = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_campioni.setFont(font)
        self.pushButton_remove_row_campioni.setObjectName(_fromUtf8("pushButton_remove_row_campioni"))
        self.gridLayout_14.addWidget(self.pushButton_remove_row_campioni, 6, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_14.addWidget(self.label_23, 7, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_19.addWidget(self.line_4, 1, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lineEdit_data_schedatura = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_data_schedatura.setText(_fromUtf8(""))
        self.lineEdit_data_schedatura.setObjectName(_fromUtf8("lineEdit_data_schedatura"))
        self.gridLayout_12.addWidget(self.lineEdit_data_schedatura, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.comboBox_schedatore = QtGui.QComboBox(self.tab_3)
        self.comboBox_schedatore.setEditable(True)
        self.comboBox_schedatore.setObjectName(_fromUtf8("comboBox_schedatore"))
        self.comboBox_schedatore.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_schedatore, 0, 0, 1, 2)
        self.label_35 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_13, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_insert_row_documentazione = QtGui.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_documentazione.setFont(font)
        self.pushButton_insert_row_documentazione.setObjectName(_fromUtf8("pushButton_insert_row_documentazione"))
        self.horizontalLayout_5.addWidget(self.pushButton_insert_row_documentazione)
        self.pushButton_remove_row_documentazione = QtGui.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_documentazione.setFont(font)
        self.pushButton_remove_row_documentazione.setObjectName(_fromUtf8("pushButton_remove_row_documentazione"))
        self.horizontalLayout_5.addWidget(self.pushButton_remove_row_documentazione)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tableWidget_documentazione = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_documentazione.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_documentazione.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_documentazione.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_documentazione.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_documentazione.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_documentazione.setRowCount(1)
        self.tableWidget_documentazione.setColumnCount(2)
        self.tableWidget_documentazione.setObjectName(_fromUtf8("tableWidget_documentazione"))
        self.tableWidget_documentazione.setColumnCount(2)
        self.tableWidget_documentazione.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.tableWidget_documentazione, 3, 0, 1, 3)
        self.pushButton_draw_doc = QtGui.QPushButton(self.tab_5)
        self.pushButton_draw_doc.setObjectName(_fromUtf8("pushButton_draw_doc"))
        self.gridLayout_9.addWidget(self.pushButton_draw_doc, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.dockWidget = QtGui.QDockWidget(self.tab_4)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_18 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 419, 235))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_20 = QtGui.QGridLayout(self.page)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_36 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_20.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_20.addWidget(self.label_9, 1, 0, 1, 2)
        self.comboBox_sito_rappcheck = QtGui.QComboBox(self.page)
        self.comboBox_sito_rappcheck.setEnabled(True)
        self.comboBox_sito_rappcheck.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito_rappcheck.setFont(font)
        self.comboBox_sito_rappcheck.setMouseTracking(True)
        self.comboBox_sito_rappcheck.setEditable(False)
        self.comboBox_sito_rappcheck.setMaxVisibleItems(99999)
        self.comboBox_sito_rappcheck.setMaxCount(2147483647)
        self.comboBox_sito_rappcheck.setObjectName(_fromUtf8("comboBox_sito_rappcheck"))
        self.comboBox_sito_rappcheck.addItem(_fromUtf8(""))
        self.gridLayout_20.addWidget(self.comboBox_sito_rappcheck, 2, 0, 1, 3)
        self.label_70 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_20.addWidget(self.label_70, 3, 0, 1, 2)
        self.label_48 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_20.addWidget(self.label_48, 6, 0, 1, 1)
        self.pushButton_crea_codice_periodo = QtGui.QPushButton(self.page)
        self.pushButton_crea_codice_periodo.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_crea_codice_periodo.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crea_codice_periodo.setIcon(icon12)
        self.pushButton_crea_codice_periodo.setObjectName(_fromUtf8("pushButton_crea_codice_periodo"))
        self.gridLayout_20.addWidget(self.pushButton_crea_codice_periodo, 6, 1, 1, 2)
        self.lineEdit_codice_periodo = QtGui.QLineEdit(self.page)
        self.lineEdit_codice_periodo.setEnabled(False)
        self.lineEdit_codice_periodo.setObjectName(_fromUtf8("lineEdit_codice_periodo"))
        self.gridLayout_20.addWidget(self.lineEdit_codice_periodo, 6, 3, 1, 1)
        self.label_45 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_20.addWidget(self.label_45, 7, 0, 1, 1)
        self.pushButton_export_matrix = QtGui.QPushButton(self.page)
        self.pushButton_export_matrix.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_export_matrix.setFont(font)
        self.pushButton_export_matrix.setIcon(icon12)
        self.pushButton_export_matrix.setObjectName(_fromUtf8("pushButton_export_matrix"))
        self.gridLayout_20.addWidget(self.pushButton_export_matrix, 7, 1, 1, 2)
        self.pushButton_orderLayers = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_orderLayers.setFont(font)
        self.pushButton_orderLayers.setObjectName(_fromUtf8("pushButton_orderLayers"))
        self.gridLayout_20.addWidget(self.pushButton_orderLayers, 8, 0, 1, 1)
        self.lineEditOrderLayer = QtGui.QLineEdit(self.page)
        self.lineEditOrderLayer.setEnabled(True)
        self.lineEditOrderLayer.setObjectName(_fromUtf8("lineEditOrderLayer"))
        self.gridLayout_20.addWidget(self.lineEditOrderLayer, 8, 1, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(20, 209, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem8, 9, 2, 1, 1)
        self.comboBox_area_rappcheck = QtGui.QComboBox(self.page)
        self.comboBox_area_rappcheck.setObjectName(_fromUtf8("comboBox_area_rappcheck"))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.gridLayout_20.addWidget(self.comboBox_area_rappcheck, 2, 3, 1, 1)
        self.pushButton_rapp_check = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rapp_check.setFont(font)
        self.pushButton_rapp_check.setIcon(icon12)
        self.pushButton_rapp_check.setObjectName(_fromUtf8("pushButton_rapp_check"))
        self.gridLayout_20.addWidget(self.pushButton_rapp_check, 3, 2, 1, 1)
        self.line = QtGui.QFrame(self.page)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_20.addWidget(self.line, 4, 0, 1, 4)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 676, 336))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_38 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_21.addWidget(self.label_38, 0, 0, 1, 2)
        self.label_46 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_21.addWidget(self.label_46, 0, 2, 1, 2)
        self.toolButtonGis = QtGui.QToolButton(self.page_2)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/GIS.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon13)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName(_fromUtf8("toolButtonGis"))
        self.gridLayout_21.addWidget(self.toolButtonGis, 1, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_21.addWidget(self.label_40, 2, 0, 1, 2)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        self.pushButton_showSelectedFeatures.setIcon(icon12)
        self.pushButton_showSelectedFeatures.setObjectName(_fromUtf8("pushButton_showSelectedFeatures"))
        self.gridLayout_21.addWidget(self.pushButton_showSelectedFeatures, 3, 0, 1, 2)
        self.label_39 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_21.addWidget(self.label_39, 4, 0, 1, 3)
        self.toolButtonPreview = QtGui.QToolButton(self.page_2)
        self.toolButtonPreview.setToolTip(_fromUtf8(""))
        self.toolButtonPreview.setIcon(icon13)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName(_fromUtf8("toolButtonPreview"))
        self.gridLayout_21.addWidget(self.toolButtonPreview, 5, 0, 1, 1)
        self.toolButtonPan = QtGui.QToolButton(self.page_2)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon14)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName(_fromUtf8("toolButtonPan"))
        self.gridLayout_21.addWidget(self.toolButtonPan, 5, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_21.addWidget(self.label_44, 6, 0, 1, 2)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.page_2)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon15)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName(_fromUtf8("toolButtonPreviewMedia"))
        self.gridLayout_21.addWidget(self.toolButtonPreviewMedia, 7, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 201, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem9, 8, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem10, 8, 1, 1, 1)
        self.pushButton_showLayer = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showLayer.setFont(font)
        self.pushButton_showLayer.setIcon(icon12)
        self.pushButton_showLayer.setObjectName(_fromUtf8("pushButton_showLayer"))
        self.gridLayout_21.addWidget(self.pushButton_showLayer, 1, 2, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.pushButton_exp_index_us = QtGui.QPushButton(self.page_3)
        self.pushButton_exp_index_us.setGeometry(QtCore.QRect(191, 20, 150, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index_us.setFont(font)
        self.pushButton_exp_index_us.setIcon(icon12)
        self.pushButton_exp_index_us.setObjectName(_fromUtf8("pushButton_exp_index_us"))
        self.label_41 = QtGui.QLabel(self.page_3)
        self.label_41.setGeometry(QtCore.QRect(6, -6, 179, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.pushButton_pdf_exp = QtGui.QPushButton(self.page_3)
        self.pushButton_pdf_exp.setGeometry(QtCore.QRect(6, 20, 179, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        self.pushButton_pdf_exp.setIcon(icon12)
        self.pushButton_pdf_exp.setObjectName(_fromUtf8("pushButton_pdf_exp"))
        self.pushButton_exp_tavole = QtGui.QPushButton(self.page_3)
        self.pushButton_exp_tavole.setGeometry(QtCore.QRect(10, 60, 171, 24))
        self.pushButton_exp_tavole.setObjectName(_fromUtf8("pushButton_exp_tavole"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_18.addWidget(self.toolBox, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout_8.addWidget(self.dockWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 4, 0, 1, 2)

        self.retranslateUi(DialogUS)
        self.tabWidget.setCurrentIndex(3)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DialogUS)

    def retranslateUi(self, DialogUS):
        DialogUS.setWindowTitle(QtGui.QApplication.translate("DialogUS", "pyArchInit Gestione Scavi - Scheda US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogUS", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogUS", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogUS", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogUS", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogUS", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogUS", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogUS", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogUS", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogUS", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogUS", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogUS", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogUS", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogUS", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogUS", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogUS", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogUS", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogUS", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogUS", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogUS", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogUS", "Connection test", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("DialogUS", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(0, QtGui.QApplication.translate("DialogUS", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(1, QtGui.QApplication.translate("DialogUS", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(2, QtGui.QApplication.translate("DialogUS", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(3, QtGui.QApplication.translate("DialogUS", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(4, QtGui.QApplication.translate("DialogUS", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(5, QtGui.QApplication.translate("DialogUS", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(6, QtGui.QApplication.translate("DialogUS", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(7, QtGui.QApplication.translate("DialogUS", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(8, QtGui.QApplication.translate("DialogUS", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(9, QtGui.QApplication.translate("DialogUS", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(10, QtGui.QApplication.translate("DialogUS", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(11, QtGui.QApplication.translate("DialogUS", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(12, QtGui.QApplication.translate("DialogUS", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(13, QtGui.QApplication.translate("DialogUS", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(14, QtGui.QApplication.translate("DialogUS", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(15, QtGui.QApplication.translate("DialogUS", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(16, QtGui.QApplication.translate("DialogUS", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(17, QtGui.QApplication.translate("DialogUS", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(18, QtGui.QApplication.translate("DialogUS", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(19, QtGui.QApplication.translate("DialogUS", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogUS", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogUS", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogUS", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(0, QtGui.QApplication.translate("DialogUS", "Attivita\' di cantiere", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(1, QtGui.QApplication.translate("DialogUS", "Abbandono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(2, QtGui.QApplication.translate("DialogUS", "Fognatura", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(3, QtGui.QApplication.translate("DialogUS", "Fondazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(4, QtGui.QApplication.translate("DialogUS", "Fossa da grano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(5, QtGui.QApplication.translate("DialogUS", "Livellamento", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(6, QtGui.QApplication.translate("DialogUS", "Muro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(7, QtGui.QApplication.translate("DialogUS", "Pavimentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(8, QtGui.QApplication.translate("DialogUS", "Pavimentazione a mosaico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(9, QtGui.QApplication.translate("DialogUS", "Palo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogUS", "Definizione stratigrafica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogUS", "Definizione Interpretata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogUS", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione.setHtml(QtGui.QApplication.translate("DialogUS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:13pt;\"><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogUS", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogUS", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogUS", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogUS", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogUS", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogUS", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DialogUS", "Attivita\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DialogUS", "Struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogUS", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogUS", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogUS", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DialogUS", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_metodo.setItemText(0, QtGui.QApplication.translate("DialogUS", "Meccanico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_metodo.setItemText(1, QtGui.QApplication.translate("DialogUS", "Stratigrafico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("DialogUS", "Metodo di scavo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogUS", "Anno", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scavato.setItemText(1, QtGui.QApplication.translate("DialogUS", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scavato.setItemText(2, QtGui.QApplication.translate("DialogUS", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogUS", "Scavato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogUS", "Rapporti stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rapporti.setText(QtGui.QApplication.translate("DialogUS", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_rapporti.setText(QtGui.QApplication.translate("DialogUS", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUS", "Tipo di rapporto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogUS", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_go_to_us.setText(QtGui.QApplication.translate("DialogUS", "Vai all\'US", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogUS", "Periodizzazione - Rapporti Stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_formazione.setItemText(0, QtGui.QApplication.translate("DialogUS", "Antropico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_formazione.setItemText(1, QtGui.QApplication.translate("DialogUS", "Naturale", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_inclusi.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUS", "Inclusi", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_campioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUS", "                     Campioni                ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DialogUS", "Formazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(0, QtGui.QApplication.translate("DialogUS", "Marrone", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(1, QtGui.QApplication.translate("DialogUS", "Marrone chiaro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(2, QtGui.QApplication.translate("DialogUS", "Marrone scuro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(3, QtGui.QApplication.translate("DialogUS", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(4, QtGui.QApplication.translate("DialogUS", "Giallo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(5, QtGui.QApplication.translate("DialogUS", "Giallo scuro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(6, QtGui.QApplication.translate("DialogUS", "Giallo chiaro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(7, QtGui.QApplication.translate("DialogUS", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(9, QtGui.QApplication.translate("DialogUS", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DialogUS", "Colore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(0, QtGui.QApplication.translate("DialogUS", "Argillosa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(1, QtGui.QApplication.translate("DialogUS", "Compatta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(2, QtGui.QApplication.translate("DialogUS", "Friabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(3, QtGui.QApplication.translate("DialogUS", "Sabbiosa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(4, QtGui.QApplication.translate("DialogUS", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(6, QtGui.QApplication.translate("DialogUS", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("DialogUS", "Consistenza", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(0, QtGui.QApplication.translate("DialogUS", "Insufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(1, QtGui.QApplication.translate("DialogUS", "Scarso", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(2, QtGui.QApplication.translate("DialogUS", "Buono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(3, QtGui.QApplication.translate("DialogUS", "Discreto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(4, QtGui.QApplication.translate("DialogUS", "Ottimo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_inclusi.setText(QtGui.QApplication.translate("DialogUS", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_inclusi.setText(QtGui.QApplication.translate("DialogUS", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_campioni.setText(QtGui.QApplication.translate("DialogUS", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_campioni.setText(QtGui.QApplication.translate("DialogUS", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("DialogUS", "Stato di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("DialogUS", "Data schedatura", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_schedatore.setItemText(0, QtGui.QApplication.translate("DialogUS", "Luca Mandolesi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("DialogUS", "Schedatore", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogUS", "Dati Fisici - Dati Schedatore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_documentazione.setText(QtGui.QApplication.translate("DialogUS", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_documentazione.setText(QtGui.QApplication.translate("DialogUS", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_documentazione.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUS", "Tipo documentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_documentazione.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogUS", "Riferimenti", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_draw_doc.setText(QtGui.QApplication.translate("DialogUS", "Visualizza documentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("DialogUS", "Documentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("DialogUS", "TOOLS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogUS", "Selezione del sito per i controlli", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito_rappcheck.setItemText(0, QtGui.QApplication.translate("DialogUS", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("DialogUS", "Check rapporti stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("DialogUS", "Crea Codice Periodo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crea_codice_periodo.setToolTip(QtGui.QApplication.translate("DialogUS", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crea_codice_periodo.setText(QtGui.QApplication.translate("DialogUS", "Crea codice periodo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("DialogUS", "Esporta Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setToolTip(QtGui.QApplication.translate("DialogUS", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setText(QtGui.QApplication.translate("DialogUS", "export Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_orderLayers.setText(QtGui.QApplication.translate("DialogUS", "Ordine Stratigrafico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(0, QtGui.QApplication.translate("DialogUS", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(1, QtGui.QApplication.translate("DialogUS", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(2, QtGui.QApplication.translate("DialogUS", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(3, QtGui.QApplication.translate("DialogUS", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(4, QtGui.QApplication.translate("DialogUS", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(5, QtGui.QApplication.translate("DialogUS", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(6, QtGui.QApplication.translate("DialogUS", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(7, QtGui.QApplication.translate("DialogUS", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(8, QtGui.QApplication.translate("DialogUS", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area_rappcheck.setItemText(9, QtGui.QApplication.translate("DialogUS", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setToolTip(QtGui.QApplication.translate("DialogUS", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setText(QtGui.QApplication.translate("DialogUS", "Check, go!!!!", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("DialogUS", "Sistemi di controllo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("DialogUS", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("DialogUS", "Disegna US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setText(QtGui.QApplication.translate("DialogUS", "GIS Data Visualizer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(QtGui.QApplication.translate("DialogUS", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("DialogUS", "Apri schede US selezionate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setToolTip(QtGui.QApplication.translate("DialogUS", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setText(QtGui.QApplication.translate("DialogUS", "Apri schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("DialogUS", "Attivazione Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(QtGui.QApplication.translate("DialogUS", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(QtGui.QApplication.translate("DialogUS", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(QtGui.QApplication.translate("DialogUS", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setText(QtGui.QApplication.translate("DialogUS", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(QtGui.QApplication.translate("DialogUS", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("DialogUS", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(QtGui.QApplication.translate("DialogUS", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setToolTip(QtGui.QApplication.translate("DialogUS", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setText(QtGui.QApplication.translate("DialogUS", "Disegna US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("DialogUS", "Funzioni di controllo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_index_us.setText(QtGui.QApplication.translate("DialogUS", "Elenco US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("DialogUS", "Esportazioni PDF/PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(QtGui.QApplication.translate("DialogUS", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("DialogUS", "Singole schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_tavole.setText(QtGui.QApplication.translate("DialogUS", "Espotazione Tavole", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("DialogUS", "Esportazioni", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("DialogUS", "Tools", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
